"""
Django settings for inspercode_case project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY não definida. Defina a variável de ambiente SECRET_KEY "
        "(ex.: no arquivo ICC-backend/.env)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]

# Só entra em vigor quando DEBUG=False (publicação de verdade); em
# desenvolvimento local (DEBUG=True) fica tudo como já era, sem exigir
# HTTPS nem cookies marcados como seguros.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Só é seguro confiar no cabeçalho X-Forwarded-Proto quando existe de fato um
# proxy reverso na frente do Django removendo qualquer valor que o cliente
# tente forjar; por isso é opt-in por variável de ambiente, não ligado
# automaticamente junto com SECURE_SSL_REDIRECT. Sem isso configurado atrás de
# um proxy que termina TLS, o Django nunca vê a requisição como segura e
# entra em loop de redirecionamento.
if os.environ.get('BEHIND_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'website.apps.WebsiteConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'inspercode_case.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inspercode_case.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'iccsite'),
        'USER': os.environ.get('DB_USER', 'iccuser'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'iccpassword'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'website' / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'images',
]

# Media files (Upload) — armazenados no Cloudinary em produção/dev compartilhado
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'images'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}
# Sem credenciais Cloudinary (ambiente local sem acesso ao dev compartilhado),
# cai para armazenamento em disco (MEDIA_ROOT) em vez de quebrar os uploads.
if CLOUDINARY_STORAGE['CLOUD_NAME']:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Limita quantas vezes o mesmo IP consegue enviar o formulário de contato,
# já que cada envio dispara um email de verdade.
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        'contact': '5/hour',
    },
}

# Configurável por ambiente pelo mesmo motivo de ALLOWED_HOSTS: o domínio
# real de produção só existe quando a hospedagem for definida. Sem
# CORS_ALLOWED_ORIGINS no ambiente, cai nas portas padrão de desenvolvimento.
CORS_ALLOWED_ORIGINS = [h for h in os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://localhost:3000'
).split(',') if h]

# Email (SendGrid)
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
EMAIL_DESTINATARIO = os.environ.get('EMAIL_DESTINATARIO', '')
EMAIL_REMETENTE = os.environ.get('EMAIL_REMETENTE', 'noreply@inspercode.com.br')